name: Monitor Webpage

on:
  schedule:
    - cron: '7 * * * *' 
  workflow_dispatch: 

jobs:
  check_webpage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run webpage check
      run: python download_and_compare.py
      
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update webpage $(date +'%Y-%m-%d %H:%M:%S')" && git push)